<GCSMUserList>
	<GCSMUser>
		<primaryKey>1</primaryKey>
		<loginID>greeng</loginID>
		<clinicalACL>
			<ClinicalAccess>
				<primaryKey>1</primaryKey>
				<permissions/>
				<negative>false</negative>
				<siteID>CC01-001-001</siteID>
				<principal/>
				<studyID>CC01-001</studyID>
				<protocolSiteCode/>
				<securityRole>Clinical Site Monitor[IssueCreate]</securityRole>
			</ClinicalAccess>
		</clinicalACL>
		<siteIDs>
			<String>CC01-001-001</String>
		</siteIDs>
		<managerUserID>1</managerUserID>
		<studyIDs>
			<String>CC01-001</String>
		</studyIDs>
		<email>ggreen@bms.com</email>
		<name>Green, Greg</name>
		<firstName>Greg</firstName>
		<lastName>Green</lastName>
	</GCSMUser>
	<GCSMUser>
		<primaryKey>2</primaryKey>
		<loginID>swalker</loginID>
		<clinicalACL/>
		<siteIDs/>
		<managerUserID>1</managerUserID>
		<studyIDs/>
		<email>swalker@bms.com</email>
		<name>Walker, Shonya</name>
		<firstName>Shonya</firstName>
		<lastName>Walker</lastName>
	</GCSMUser>
	<GCSMUser>
		<primaryKey>3</primaryKey>
		<loginID>yman</loginID>
		<clinicalACL/>
		<siteIDs/>
		<managerUserID>1</managerUserID>
		<studyIDs/>
		<email>yman@bms.com</email>
		<name>Man, Syo</name>
		<firstName>Yo</firstName>
		<lastName>Man</lastName>
	</GCSMUser>
</GCSMUserList>
